#!/bin/bash

# ============================================================================
# COMANDOS DE MANTENIMIENTO PARA TU APLICACIÓN EN EC2
# ============================================================================

echo "=== COMANDOS DE MANTENIMIENTO ==="
echo ""

echo "1. PARAR LA APLICACIÓN"
echo "===================="
echo "sudo docker-compose -f docker-compose.prod.yml down"
echo ""

echo "2. INICIAR LA APLICACIÓN"
echo "======================"
echo "sudo docker-compose -f docker-compose.prod.yml up -d"
echo ""

echo "3. REINICIAR LA APLICACIÓN"
echo "========================="
echo "sudo docker-compose -f docker-compose.prod.yml restart"
echo ""

echo "4. VER LOGS EN TIEMPO REAL"
echo "========================="
echo "# Todos los servicios"
echo "sudo docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo "# Solo la aplicación"
echo "sudo docker-compose -f docker-compose.prod.yml logs -f bulksms-api"
echo ""
echo "# Solo la base de datos"
echo "sudo docker-compose -f docker-compose.prod.yml logs -f bulksms-mysql"
echo ""

echo "5. VER ESTADO DE LOS CONTENEDORES"
echo "================================"
echo "sudo docker ps"
echo "sudo docker-compose -f docker-compose.prod.yml ps"
echo ""

echo "6. ENTRAR AL CONTENEDOR DE LA APLICACIÓN"
echo "======================================="
echo "sudo docker exec -it bulksms-api-prod bash"
echo ""

echo "7. ENTRAR A LA BASE DE DATOS"
echo "==========================="
echo "sudo docker exec -it bulksms-mysql-prod mysql -u root -p"
echo ""

echo "8. HACER BACKUP DE LA BASE DE DATOS"
echo "=================================="
echo 'sudo docker exec bulksms-mysql-prod mysqldump -u root -p bulksmsdb > backup-$(date +%Y%m%d-%H%M%S).sql'
echo ""

echo "9. RESTAURAR BACKUP DE LA BASE DE DATOS"
echo "======================================"
echo "sudo docker exec -i bulksms-mysql-prod mysql -u root -p bulksmsdb < backup-archivo.sql"
echo ""

echo "10. ACTUALIZAR LA APLICACIÓN (REBUILD)"
echo "====================================="
echo "sudo docker-compose -f docker-compose.prod.yml down"
echo "sudo docker-compose -f docker-compose.prod.yml up -d --build"
echo ""

echo "11. LIMPIAR CONTENEDORES E IMÁGENES NO USADAS"
echo "============================================="
echo "sudo docker system prune -a"
echo ""

echo "12. VER USO DE RECURSOS"
echo "======================"
echo "sudo docker stats"
echo ""

echo "13. VERIFICAR CONECTIVIDAD"
echo "========================="
echo "# Health check interno"
echo "curl http://localhost:8080/actuator/health"
echo ""
echo "# Test desde fuera (reemplaza IP)"
echo "curl http://TU-IP-EC2:8080/actuator/health"
echo ""

echo "14. VER VARIABLES DE ENTORNO"
echo "=========================="
echo "sudo docker-compose -f docker-compose.prod.yml config"
echo ""

echo "15. TROUBLESHOOTING - CONTENEDOR NO ARRANCA"
echo "=========================================="
echo "# Ver logs detallados"
echo "sudo docker-compose -f docker-compose.prod.yml logs --tail=100 bulksms-api"
echo ""
echo "# Verificar que MySQL está corriendo"
echo "sudo docker-compose -f docker-compose.prod.yml ps bulksms-mysql"
echo ""
echo "# Probar conexión a MySQL"
echo "sudo docker exec bulksms-mysql-prod mysqladmin ping -h localhost"
echo ""

echo "16. TROUBLESHOOTING - PROBLEMAS DE CONECTIVIDAD"
echo "=============================================="
echo "# Verificar puertos abiertos"
echo "sudo netstat -tlnp | grep :8080"
echo "sudo netstat -tlnp | grep :3306"
echo ""
echo "# Verificar firewall"
echo "sudo systemctl status firewalld"
echo ""
echo "# Verificar Security Group en AWS Console:"
echo "# - Puerto 8080 (HTTP Custom TCP)"
echo "# - Puerto 22 (SSH)"
echo "# - Puerto 80 (HTTP) - opcional"
echo "# - Puerto 443 (HTTPS) - opcional"
echo ""

echo "===================================================="
echo "COMANDOS RÁPIDOS PARA COPY-PASTE:"
echo ""
echo "# Ver logs rápido:"
echo "sudo docker-compose -f docker-compose.prod.yml logs --tail=50"
echo ""
echo "# Reiniciar todo:"
echo "sudo docker-compose -f docker-compose.prod.yml restart"
echo ""
echo "# Rebuild completo:"
echo "sudo docker-compose -f docker-compose.prod.yml down && sudo docker-compose -f docker-compose.prod.yml up -d --build"
echo ""
echo "# Health check:"
echo "curl http://localhost:8080/actuator/health"
echo "===================================================="
